### ISSUE TITLE
UI Scaling is off

### ISSUE THREAD

**Issue by ZachR08** [FluffyMaguro/SC2_Coop_overlay#11]
![SC Overlay](https://user-images.githubusercontent.com/72525542/95384604-dc6cf700-08ba-11eb-8d24-c5e4579a9da7.jpg)

When I open the overlay, the UI scaling is off to the point I can't read it at all. My resolution is 3840x2160 @ 300% on 75in LG TV.

**Comment by FluffyMaguro** [comment]
I added some fix on the GitHub. I can send you a packaged version tomorrow for you to try.

**Comment by ZachR08** [comment]
Awesome

**Comment by FluffyMaguro** [comment]
Try this beta
https://mega.nz/file/g9FGWDZA#hPb-Rth7zl8uc2anV81a9m5FH9URxir3S6Yi45lkIP8

**Comment by ZachR08** [comment]
yeah that looks great! Thanks for your time!

**Comment by FluffyMaguro** [comment]
Nice
