### ISSUE TITLE
Team games are recognized as co-op games

### ISSUE THREAD

**Issue by conn** [FluffyMaguro/SC2_Coop_overlay#12]
The overlay pops up upon finishing a team game, regardless of 2v2, 3v3, or 4v4. I know we discussed this before over Discord and you mentioned that there isn't really a way to distinguish between the two because the replay format is more or less the same.

Would it be possible to distinguish based on the names of the participants? Names like "Purifier Hologram", "Megalith", "BonusNeutral", "Amon's Forces", "Kel-Morian Equipment", "Molten Salamander", "Sgt. Hammer's Forces", and etcetera don't or can't show up on the ladder. It may not be a simple fix, but it certainly seems possible.

**Comment by FluffyMaguro** [comment]
Hi, yeah it would be possible. Although it could break it for non-official maps.
I could add a checkbox somewhere, and then sort based on that, but it's a low priority now.
I suggest to either close the app, hide the overlay with the checkbox, or use hotkeys to hide the overlay when it comes up.

**Comment by conn** [comment]
I didn't think of the non-official maps. That's a great point.
