### ISSUE TITLE
"NO DC" displayed in top when sc2 overlay is running?

### ISSUE THREAD

**Issue by destromano** [FluffyMaguro/SC2_Coop_overlay#19]
As soon as the sc2 overlay program runs, until it exits, "NO DC" is displayed at the top of the screen. This happens if the overlay is hidden or shown. Can't say for sure when this started happening. Did a little grepping of the code but didn't find anything.

Pic attached (look right above CUSTOM GAME)

![wtf](https://user-images.githubusercontent.com/635071/122622537-0b9d5000-d067-11eb-80f6-28969835e002.png)

Btw you've made incredible progress on this since I took a break from SC2, amazing to see how much this overlay has changed even though sc2 is in maintence mode. So thanks for the amazing work!

**Comment by FluffyMaguro** [comment]
Check if it's not twitch chat or performance overlay.

**Comment by destromano** [comment]
Dosen't seem related to either. Only thing that hides it is settings -> "dont show overlay on screen". Will dig a little more

**Comment by destromano** [comment]
Alright this was an issue with NVIDIA deciding to hook into the overlay, so I'll close this

https://www.reddit.com/r/godot/comments/lpgyyy/no_dc_in_upper_left_corner/gxunpr8/
