### ISSUE TITLE
Windows Defender registers SCO as malicious

### ISSUE THREAD

**Issue by Fra-nk** [FluffyMaguro/SC2_Coop_Overlay#28]
Hi,
I know that there is probably not _so much_ that you can do and it is not necessarily a bug/issue of SCO itself, but I think this might still be the best place to register it - even if it is only for making it obvious to everyone.

I downloaded SCO directly from GitHub, extracted it and the newest Microsoft Defender raised an alert for
`Trojan:Win32/Zpevdo.B`.

**Comment by conn** [comment]
Ugh, it looks like this is a pretty common issue with compiled Python apps. The only solutions seem to be either chasing down each AV and submitting false positives yourself (I found a list [here](https://github.com/hankhank10/false-positive-malware-reporting)) or signing it (which costs some money and time).

**Comment by FluffyMaguro** [comment]
I submitted it to Microsoft for review. Thanks for the link.

I also recently added support for compiling the app with [Nuitka](https://nuitka.net/), it got only 1/66 score, but it's not working 100% (particularly websockets package doesn't).

**Comment by conn** [comment]
It's so frustrating that this is a problem. If you want someone to jump through these hoops for you, I don't mind doing it. I'm not sure what level of privilege I need to the repository for it, though.

**Comment by FluffyMaguro** [comment]
It's fine. It should be whitelisted by Microsoft now.

**Comment by conn** [comment]
Thanks!
