### ISSUE TITLE
Ally Commander - Prestige / Kill %

### ISSUE THREAD

**Issue by datachildx** [FluffyMaguro/SC2_Coop_Overlay#34]
Hi Maguro, love what you do. One of the metrics I was looking for is Commander / Prestige / Kill %. Currently % kill is grouped to the commander. Also an ability to export the cache analyzed file.

**Comment by FluffyMaguro** [comment]
Hi, there is a "Dump Data" button in "statistics" tab that will export analyzed data into a json file (replay_data_dump.json).
You could also open the cache (cache_overall_stats) with Python directly, it's a pickled Python object.
And then you can do any analysis on it as you wish.

**Comment by datachildx** [comment]
Thank you!, I didn't realize that's what that button meant. Appreciate the
quick response.
